[profile.default]
src = 'src'
out = 'out'
libs = ['lib', 'node_modules']
test = 'test'
solc_version = '0.8.29'
optimizer = true
optimizer_runs = 1000
via_ir = true
ffi = true
revert_strings = 'strip'
remappings = [
    'forge-std/=lib/forge-std/src/',
    '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/',
    'v4-core/=lib/v4-core/src/',
]

[profile.default.vyper]
version = "0.3.10"

[profile.test]
ffi = true

[profile.test.fuzz]
runs = 500

[profile.ci]
ffi = false
no_match_test = "(Integration|Fork)"

[fmt]
line_length = 120

[fuzz]
dictionary_weight = 80
include_storage = true
include_push_bytes = true
